version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - npm install -g serverless
  build:
    commands:
      - npm install
      - npm run build:prod
      - mv .webpack/* .
      - serverless package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - .serverless/loyaltyoneassignment.zip

    