swagger: "2.0"
info:
  version: "1.0.0"
  title: "LoyaltyOne"
  description: "LoyaltyOne Assignment APIs"
host: "j0jjemeyy5.execute-api.us-east-1.amazonaws.com"
basePath: '/dev/api'
schemes:
- "https"
paths:
  /entry:
    post:
      consumes:
        - application/json
      description: "Add entry."
      parameters:
        - in: body
          name: entry
          required: true
          schema:
            $ref: "#/definitions/entryRequest"
      responses:
        200:
          description: "Adds a top level entry."
          schema:
            $ref: "#/definitions/entryadd"
  /entry/{id}/response:
    post:
      consumes:
        - application/json
      description: "Respond to an entry"
      parameters:
        - in: "path"    
          name: id
          required: true
          type: "string"
          description: "Entry ID for which a response is being submitted."
        - in: body
          name: entry
          required: true
          schema:
            $ref: "#/definitions/entryRequest"
      responses:
        200:
          description: "Adds a response to an entry."
          schema:
            $ref: "#/definitions/entryadd"
  /entries:
    get:
      responses:
        200:
          description: "Returns all top level entries."
          schema:
            $ref: "#/definitions/entries"
  /entry/{id}/responses:
    get:
      parameters:
      - name: id
        in: "path"
        required: true
        type: "string"
        description: "Entry id to return all responses."
      responses:
        200:
          description: "Returns all responses for a particular entry."
          schema:
            $ref: "#/definitions/entries"
definitions:
  entryRequest:
    type: object
    properties:
      username:
        type: "string"
      city:
        type: "string"
      text:
        type: "string"
  entries:
    type: object
    properties:
      results:
        type: array
        items:
          $ref: '#/definitions/entry'
  entry:
    type: object
    properties:
      id:
        type: "string"
      username:
        type: "string"
      city:
        type: "string"
      text:
        type: "string"
      parent_id:
        type: "string"
      createdAt:
        type: "string"
      updatedAt:
        type: "string"
  entryadd:
    type: object
    properties:
      status:
        type: "string"
      result:
        type: object
        items:
          $ref: '#/definitions/entry'